#!/bin/bash
set -e

SITE_DIR="docs"
PROJECT_NAME="ai-newsletter"

mkdir -p "$SITE_DIR/reports"

# Normalize titles before processing
./scripts/normalize-md.sh

# Find and convert all markdown files in output/
find output -name "*.md" -type f | while read -r md_file; do
    echo "Processing: $md_file"
    
    # Get relative path and create HTML path
    rel_path="${md_file#output/}"
    html_path="$SITE_DIR/reports/${rel_path%.md}.html"
    
    # Create directory
    mkdir -p "$(dirname "$html_path")"
    
    # Extract title from first h1
    title=$(grep -m1 "^# " "$md_file" | sed 's/^# //' || echo "AI Daily Newsletter")
    
    # Create temp file with full HTML
    temp_file=$(mktemp)
    
    # Write header
    cat > "$temp_file" << EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="/$PROJECT_NAME/assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🤖 AI Daily Newsletter</h1>
            <nav>
                <a href="/$PROJECT_NAME/">最新</a>
                <a href="/$PROJECT_NAME/archive.html">歷史存檔</a>
                <a href="/$PROJECT_NAME/search.html">搜尋文章</a>
            </nav>
        </header>
        <main>
EOF
    
    # Convert markdown to HTML and append
    pandoc "$md_file" -f markdown -t html --wrap=none >> "$temp_file"
    
    # Write footer
    cat >> "$temp_file" << 'EOF'
        </main>
        <footer>
            <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
        </footer>
    </div>
</body>
</html>
EOF
    
    # Move to final location
    mv "$temp_file" "$html_path"
    echo "Created: $html_path"
done

# Generate index.html linking to all reports
generate_index() {
    INDEX="$SITE_DIR/index.html"
    tmp=$(mktemp)
    echo "🔧 Updating index: $INDEX"

    cat > "$tmp" << 'INDEXEOF'
<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Newsletter - 最新消息</title>
  <link rel="stylesheet" href="/ai-newsletter/assets/style.css">
</head>
<body>
  <div class="container">
    <header>
      <h1>🤖 AI Daily Newsletter</h1>
      <p>每日 AI 科技新聞摘要</p>
      <nav>
        <a href="/ai-newsletter/" class="active">最新</a>
        <a href="/ai-newsletter/archive.html">歷史存檔</a>
        <a href="/ai-newsletter/search.html">搜尋文章</a>
      </nav>
    </header>
    <main>
      <div class="section-header">
        <h2>最新報告 (最近 3 天)</h2>
      </div>
      <div class="report-grid">
INDEXEOF

    # List reports newest-first, limit to 3
    count=0
    find "$SITE_DIR/reports" -name "*.html" | sort -r | while read -r f; do
        if [ $count -ge 3 ]; then
            break
        fi
        rel="${f#$SITE_DIR/}"                 # reports/2026/02/11.html
        date_part="${rel#reports/}"          # 2026/02/11.html
        nice_date="${date_part%.html}"       # 2026/02/11
        # extract title from html <title>
        title=$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' "$f" | head -n1)
        title=${title:-$(basename "$f")}
        
        cat >> "$tmp" << EOF
        <div class="newsletter-card">
          <h3>$title</h3>
          <a href="/$PROJECT_NAME/${rel}" class="btn">閱讀內容</a>
        </div>
EOF
        count=$((count + 1))
    done

    cat >> "$tmp" << 'INDEXEOF'
      </div>
      <div class="archive-link">
        <a href="/ai-newsletter/archive.html" class="btn secondary">查看歷史存檔</a>
      </div>
    </main>
    <footer>
      <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
    </footer>
  </div>
</body>
</html>
INDEXEOF

    mv "$tmp" "$INDEX"
    echo "✅ Index updated: $INDEX"
}

# Generate archive.html listing all reports
generate_archive() {
    ARCHIVE="$SITE_DIR/archive.html"
    tmp=$(mktemp)
    echo "🔧 Updating archive: $ARCHIVE"

    cat > "$tmp" << 'ARCHIVEEOF'
<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Newsletter - 歷史存檔</title>
  <link rel="stylesheet" href="/ai-newsletter/assets/style.css">
</head>
<body>
  <div class="container">
    <header>
      <h1>🤖 AI Daily Newsletter</h1>
      <nav>
        <a href="/ai-newsletter/">最新</a>
        <a href="/ai-newsletter/archive.html" class="active">歷史存檔</a>
        <a href="/ai-newsletter/search.html">搜尋文章</a>
      </nav>
    </header>
    <main>
      <div class="section-header">
        <h2>歷史存檔</h2>
      </div>
      <div class="archive-list">
ARCHIVEEOF

    # List all reports newest-first
    last_month=""
    find "$SITE_DIR/reports" -name "*.html" | sort -r | while read -r f; do
        rel="${f#$SITE_DIR/}"
        date_part="${rel#reports/}"
        nice_date="${date_part%.html}"
        month="${nice_date%/*}"
        
        if [ "$month" != "$last_month" ]; then
            if [ "$last_month" != "" ]; then
                echo "        </ul></details>" >> "$tmp"
            fi
            echo "        <details class='month-group' open><summary><h3>$month</h3></summary><ul>" >> "$tmp"
            last_month="$month"
        fi

        title=$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' "$f" | head -n1)
        title=${title:-$(basename "$f")}
        echo "          <li><span class='date'>$nice_date</span> - <a href=\"/$PROJECT_NAME/${rel}\">$title</a></li>" >> "$tmp"
    done
    
    if [ "$last_month" != "" ]; then
        echo "        </ul></details>" >> "$tmp"
    fi

    cat >> "$tmp" << 'ARCHIVEEOF'
      </div>
    </main>
    <footer>
      <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
    </footer>
  </div>
</body>
</html>
ARCHIVEEOF

    mv "$tmp" "$ARCHIVE"
    echo "✅ Archive updated: $ARCHIVE"
}

# Generate search_data.json for client-side search
generate_search_data() {
    DATA_FILE="$SITE_DIR/assets/search_data.json"
    mkdir -p "$(dirname "$DATA_FILE")"
    tmp=$(mktemp)
    echo "[" > "$tmp"
    
    first=true
    find output -name "*.md" -type f | while read -r md_file; do
        if [ "$first" = true ]; then
            first=false
        else
            echo "," >> "$tmp"
        fi
        
        rel_path="${md_file#output/}"
        url="/$PROJECT_NAME/reports/${rel_path%.md}.html"
        title=$(grep -m1 "^# " "$md_file" | sed 's/^# //' | sed 's/"/\\"/g' || echo "AI Daily Newsletter")
        content=$(cat "$md_file" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | tr '\n' ' ')
        date_part=$(basename "$md_file" .md)
        
        echo "  {\"title\": \"$title\", \"url\": \"$url\", \"content\": \"$content\", \"date\": \"$date_part\"}" >> "$tmp"
    done
    
    echo "]" >> "$tmp"
    mv "$tmp" "$DATA_FILE"
    echo "✅ Search data updated: $DATA_FILE"
}

# Generate search.html
generate_search_page() {
    SEARCH_PAGE="$SITE_DIR/search.html"
    cat > "$SEARCH_PAGE" << 'EOF'
<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Newsletter - 搜尋</title>
  <link rel="stylesheet" href="/ai-newsletter/assets/style.css">
</head>
<body>
  <div class="container">
    <header>
      <h1>🤖 AI Daily Newsletter</h1>
      <nav>
        <a href="/ai-newsletter/">最新</a>
        <a href="/ai-newsletter/archive.html">歷史存檔</a>
        <a href="/ai-newsletter/search.html" class="active">搜尋文章</a>
      </nav>
    </header>
    <main>
      <div class="section-header">
        <h2>搜尋文章</h2>
      </div>
      <div class="search-container">
        <input type="text" id="search-input" placeholder="輸入關鍵字搜尋 (標題、日期或內容)..." autofocus>
      </div>
      <div id="search-results" class="report-grid">
        <!-- 搜尋結果將顯示在此 -->
      </div>
    </main>
    <footer>
      <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
    </footer>
  </div>
  <script>
    let searchData = [];
    
    async function loadSearchData() {
      try {
        const response = await fetch('/ai-newsletter/assets/search_data.json');
        searchData = await response.json();
      } catch (e) {
        console.error('Failed to load search data:', e);
      }
    }
    
    function performSearch(query) {
      const resultsContainer = document.getElementById('search-results');
      resultsContainer.innerHTML = '';
      
      if (!query || query.length < 1) return;
      
      const filtered = searchData.filter(item => {
        return item.title.toLowerCase().includes(query.toLowerCase()) || 
               item.content.toLowerCase().includes(query.toLowerCase()) ||
               item.date.includes(query);
      });
      
      if (filtered.length === 0) {
        resultsContainer.innerHTML = '<p>找不到符合的內容</p>';
        return;
      }
      
      filtered.forEach(item => {
        const card = document.createElement('div');
        card.className = 'newsletter-card';
        
        // Highlight logic (basic)
        let displayTitle = item.title;
        let displayContent = item.content.substring(0, 150) + '...';
        
        const regex = new RegExp(`(${query})`, 'gi');
        displayTitle = displayTitle.replace(regex, '<mark>$1</mark>');
        displayContent = displayContent.replace(regex, '<mark>$1</mark>');
        
        card.innerHTML = `
          <h3>${displayTitle}</h3>
          <div class="date">${item.date}</div>
          <div class="summary">${displayContent}</div>
          <a href="${item.url}" class="btn">閱讀全文</a>
        `;
        resultsContainer.appendChild(card);
      });
    }
    
    document.getElementById('search-input').addEventListener('input', (e) => {
      performSearch(e.target.value);
    });
    
    loadSearchData();
  </script>
</body>
</html>
EOF
    echo "✅ Search page updated: $SEARCH_PAGE"
}

generate_index
generate_archive
generate_search_data
generate_search_page

echo "✅ Build complete!"
find "$SITE_DIR/reports" -name "*.html" -type f
