#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

SITE_DIR="docs"
BASE_PATH="${BASE_PATH-/ai-newsletter}"
BASE_PATH="${BASE_PATH%/}"
while [[ "$BASE_PATH" == */ ]]; do
    BASE_PATH="${BASE_PATH%/}"
done

if [ -n "$BASE_PATH" ] && [[ "$BASE_PATH" != /* ]]; then
    echo "ERROR: BASE_PATH must be empty or start with /: $BASE_PATH" >&2
    exit 1
fi

python3 scripts/site_tools.py validate-source --output output --ledger data/news-ledger.json

rm -rf "$SITE_DIR/reports"
mkdir -p "$SITE_DIR/reports" "$SITE_DIR/assets"
rm -f "$SITE_DIR/index.html" "$SITE_DIR/archive.html" \
    "$SITE_DIR/search.html" "$SITE_DIR/assets/search_data.json"

while IFS= read -r md_file; do
    echo "Processing: $md_file"
    rel_path="${md_file#output/}"
    html_path="$SITE_DIR/reports/${rel_path%.md}.html"
    mkdir -p "$(dirname "$html_path")"

    title="$(sed -n 's/^# //p' "$md_file" | head -n 1)"
    title="${title:-AI Daily Newsletter}"
    temp_file="$(mktemp)"

    cat > "$temp_file" <<EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Orbitron:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="${BASE_PATH}/assets/style.css">
</head>
<body>
    <div class="neural-bg"></div>
    <div class="container">
        <header class="glass-effect">
            <h1 class="glow-text">AI Daily Newsletter</h1>
            <nav>
                <a href="${BASE_PATH}/">最新</a>
                <a href="${BASE_PATH}/archive.html">歷史存檔</a>
                <a href="${BASE_PATH}/search.html">搜尋文章</a>
            </nav>
        </header>
        <main>
EOF

    pandoc "$md_file" -f markdown -t html --wrap=none >> "$temp_file"

    cat >> "$temp_file" <<'EOF'
        </main>
        <footer>
            <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
        </footer>
    </div>
</body>
</html>
EOF

    mv "$temp_file" "$html_path"
    echo "Created: $html_path"
done < <(find output -name "*.md" -type f | sort)

generate_index() {
    local index="$SITE_DIR/index.html"
    local tmp
    tmp="$(mktemp)"

    cat > "$tmp" <<EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Newsletter - 最新消息</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Orbitron:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="${BASE_PATH}/assets/style.css">
</head>
<body>
  <div class="neural-bg"></div>
  <div class="container">
    <header class="glass-effect">
      <h1 class="glow-text">AI Daily Newsletter</h1>
      <p class="text-muted">每日 AI 科技新聞摘要</p>
      <nav>
        <a href="${BASE_PATH}/" class="active">最新</a>
        <a href="${BASE_PATH}/archive.html">歷史存檔</a>
        <a href="${BASE_PATH}/search.html">搜尋文章</a>
      </nav>
    </header>
    <main>
      <div class="section-header">
        <h2 class="glow-text">最新報告 (最近 3 天)</h2>
      </div>
      <div class="report-grid">
EOF

    local count=0
    local f rel title
    while IFS= read -r f; do
        if [ "$count" -ge 3 ]; then
            break
        fi
        rel="${f#$SITE_DIR/}"
        title="$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' "$f" | head -n 1)"
        title="${title:-$(basename "$f")}"
        cat >> "$tmp" <<EOF
        <div class="newsletter-card glass-effect">
          <h3>$title</h3>
          <a href="${BASE_PATH}/${rel}" class="btn shine">閱讀內容</a>
        </div>
EOF
        count=$((count + 1))
    done < <(find "$SITE_DIR/reports" -name "*.html" -type f | sort -r)

    cat >> "$tmp" <<EOF
      </div>
      <div class="archive-link">
        <a href="${BASE_PATH}/archive.html" class="btn secondary">查看歷史存檔</a>
      </div>
    </main>
    <footer>
      <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
    </footer>
  </div>
</body>
</html>
EOF

    mv "$tmp" "$index"
    echo "Index updated: $index"
}

generate_archive() {
    local archive="$SITE_DIR/archive.html"
    local tmp
    tmp="$(mktemp)"

    cat > "$tmp" <<EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Newsletter - 歷史存檔</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Orbitron:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="${BASE_PATH}/assets/style.css">
</head>
<body>
  <div class="neural-bg"></div>
  <div class="container">
    <header class="glass-effect">
      <h1 class="glow-text">AI Daily Newsletter</h1>
      <nav>
        <a href="${BASE_PATH}/">最新</a>
        <a href="${BASE_PATH}/archive.html" class="active">歷史存檔</a>
        <a href="${BASE_PATH}/search.html">搜尋文章</a>
      </nav>
    </header>
    <main>
      <div class="section-header">
        <h2 class="glow-text">歷史存檔</h2>
      </div>
      <div class="archive-list">
EOF

    local last_month=""
    local f rel date_part nice_date month title
    while IFS= read -r f; do
        rel="${f#$SITE_DIR/}"
        date_part="${rel#reports/}"
        nice_date="${date_part%.html}"
        month="${nice_date%/*}"

        if [ "$month" != "$last_month" ]; then
            if [ -n "$last_month" ]; then
                echo "        </ul></details>" >> "$tmp"
            fi
            echo "        <details class='month-group glass-effect' open><summary><h3>$month</h3></summary><ul>" >> "$tmp"
            last_month="$month"
        fi

        title="$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' "$f" | head -n 1)"
        title="${title:-$(basename "$f")}"
        echo "          <li><span class='date'>$nice_date</span> - <a href=\"${BASE_PATH}/${rel}\">$title</a></li>" >> "$tmp"
    done < <(find "$SITE_DIR/reports" -name "*.html" -type f | sort -r)

    if [ -n "$last_month" ]; then
        echo "        </ul></details>" >> "$tmp"
    fi

    cat >> "$tmp" <<'EOF'
      </div>
    </main>
    <footer>
      <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
    </footer>
  </div>
</body>
</html>
EOF

    mv "$tmp" "$archive"
    echo "Archive updated: $archive"
}

generate_search_page() {
    local search_page="$SITE_DIR/search.html"
    cat > "$search_page" <<'EOF'
<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Daily Newsletter - 搜尋</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Orbitron:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="__BASE_PATH__/assets/style.css">
</head>
<body>
  <div class="neural-bg"></div>
  <div class="container">
    <header class="glass-effect">
      <h1 class="glow-text">AI Daily Newsletter</h1>
      <nav>
        <a href="__BASE_PATH__/">最新</a>
        <a href="__BASE_PATH__/archive.html">歷史存檔</a>
        <a href="__BASE_PATH__/search.html" class="active">搜尋文章</a>
      </nav>
    </header>
    <main>
      <div class="section-header">
        <h2 class="glow-text">搜尋文章</h2>
      </div>
      <div class="search-container">
        <input type="text" id="search-input" placeholder="輸入關鍵字搜尋 (標題、日期或內容)..." autofocus>
      </div>
      <div id="search-results" class="report-grid"></div>
    </main>
    <footer>
      <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
    </footer>
  </div>
  <script>
    let searchData = [];

    async function loadSearchData() {
      try {
        const response = await fetch('__BASE_PATH__/assets/search_data.json');
        searchData = await response.json();
      } catch (error) {
        console.error('Failed to load search data:', error);
      }
    }

    function escapeRegExp(value) {
      return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }

    function appendHighlighted(parent, value, regex) {
      let offset = 0;
      for (const match of value.matchAll(regex)) {
        parent.appendChild(document.createTextNode(value.slice(offset, match.index)));
        const mark = document.createElement('mark');
        mark.textContent = match[0];
        parent.appendChild(mark);
        offset = match.index + match[0].length;
      }
      parent.appendChild(document.createTextNode(value.slice(offset)));
    }

    function performSearch(query) {
      const resultsContainer = document.getElementById('search-results');
      resultsContainer.replaceChildren();
      if (!query) return;

      const normalizedQuery = query.toLowerCase();
      const filtered = searchData.filter((item) =>
        item.title.toLowerCase().includes(normalizedQuery) ||
        item.content.toLowerCase().includes(normalizedQuery) ||
        item.date.includes(query)
      );

      if (filtered.length === 0) {
        const message = document.createElement('p');
        message.textContent = '找不到符合的內容';
        resultsContainer.appendChild(message);
        return;
      }

      const regex = new RegExp(escapeRegExp(query), 'gi');
      for (const item of filtered) {
        const card = document.createElement('div');
        card.className = 'newsletter-card glass-effect';

        const heading = document.createElement('h3');
        appendHighlighted(heading, item.title, regex);
        card.appendChild(heading);

        const date = document.createElement('div');
        date.className = 'date';
        date.textContent = item.date;
        card.appendChild(date);

        const summary = document.createElement('div');
        summary.className = 'summary';
        appendHighlighted(summary, `${item.content.substring(0, 150)}...`, regex);
        card.appendChild(summary);

        const link = document.createElement('a');
        link.href = item.url;
        link.className = 'btn shine';
        link.textContent = '閱讀全文';
        card.appendChild(link);
        resultsContainer.appendChild(card);
      }
    }

    document.getElementById('search-input').addEventListener('input', (event) => {
      performSearch(event.target.value);
    });

    loadSearchData();
  </script>
</body>
</html>
EOF

    python3 - "$search_page" "$BASE_PATH" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
path.write_text(
    path.read_text(encoding="utf-8").replace("__BASE_PATH__", sys.argv[2]),
    encoding="utf-8",
)
PY
    echo "Search page updated: $search_page"
}

generate_index
generate_archive
python3 scripts/site_tools.py generate-search --output output \
    --destination "$SITE_DIR/assets/search_data.json" --base-path "$BASE_PATH"
generate_search_page

python3 scripts/site_tools.py validate-site --output output --site docs
echo "Build complete: generated site validated successfully."
