#!/bin/bash
set -e

mkdir -p docs/reports

# Find and convert all markdown files in output/
find output -name "*.md" -type f | while read -r md_file; do
    echo "Processing: $md_file"
    
    # Get relative path and create HTML path
    rel_path="${md_file#output/}"
    html_path="docs/reports/${rel_path%.md}.html"
    
    # Create directory
    mkdir -p "$(dirname "$html_path")"
    
    # Extract title from first h1
    title=$(grep -m1 "^# " "$md_file" | sed 's/^# //' || echo "AI Daily Newsletter")
    
    # Create temp file with full HTML
    temp_file=$(mktemp)
    
    # Write header
    cat > "$temp_file" << EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="/ai-newsletter/assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🤖 AI Daily Newsletter</h1>
            <nav>
                <a href="/ai-newsletter/">← 回到首頁</a>
            </nav>
        </header>
        <main>
EOF
    
    # Convert markdown to HTML and append
    pandoc "$md_file" -f markdown -t html --wrap=none >> "$temp_file"
    
    # Write footer
    cat >> "$temp_file" << 'EOF'
        </main>
        <footer>
            <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
        </footer>
    </div>
</body>
</html>
EOF
    
    # Move to final location
    mv "$temp_file" "$html_path"
    echo "Created: $html_path"
done

echo "✅ Build complete!"
find docs/reports -name "*.html" -type f
