#!/bin/bash
# Render Markdown to HTML using pandoc

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_ROOT/output"
SITE_DIR="$PROJECT_ROOT/site"
TEMPLATE_DIR="$SITE_DIR/templates"

echo "🔄 Rendering Markdown to HTML with pandoc..."

# Create reports directory
mkdir -p "$SITE_DIR/reports"

# Check if pandoc is installed
if ! command -v pandoc &> /dev/null; then
    echo "❌ pandoc not found. Please install: sudo apt-get install pandoc"
    exit 1
fi

# Process all markdown files in output/
find "$OUTPUT_DIR" -name "*.md" | while read -r md_file; do
    # Get relative path
    rel_path="${md_file#$OUTPUT_DIR/}"
    html_path="$SITE_DIR/reports/${rel_path%.md}.html"
    
    # Create directory
    mkdir -p "$(dirname "$html_path")"
    
    echo "  Converting: $rel_path → ${rel_path%.md}.html"
    
    # Extract title from first h1
    title=$(grep -m1 "^# " "$md_file" | sed 's/^# //' || echo "AI Daily Newsletter")
    
    # Create temp file with full HTML
    temp_file=$(mktemp)
    
    # Write header
    cat > "$temp_file" << EOF
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" href="/ai-newsletter/assets/style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>🤖 AI Daily Newsletter</h1>
            <nav>
                <a href="/ai-newsletter/">← 回到首頁</a>
            </nav>
        </header>
        <main>
EOF
    
    # Convert markdown to HTML and append
    pandoc "$md_file" -f markdown -t html --wrap=none >> "$temp_file"
    
    # Write footer
    cat >> "$temp_file" << EOF
        </main>
        <footer>
            <p>Generated by OpenClaw Agent | <a href="https://github.com/BrunoLin-tw/ai-newsletter">GitHub Repo</a></p>
        </footer>
    </div>
</body>
</html>
EOF
    
    # Move to final location
    mv "$temp_file" "$html_path"
done

echo "✅ Render complete!"
echo "📁 Output: $SITE_DIR/reports/"
